### PR TITLE
CMake support for esp-mdf using idf.py

### PR DESCRIPTION
**Pull request by jesperrix**
Copied get-started and added CMake support to it as an example project.

### CODE REVIEW

**Comment by InfiniteYuan1** [comment]
CMake support for esp-mdf has been commited internally. I will push it to github as soon as possible.

Can you rebase your commit on lastest master?Thanks.

**Comment by jesperrix** [comment]
Hi @InfiniteYuan1,
Thanks for looking at my PR, yes I will rebase my commits on your latest master.
Did you verify cmake build works with what you comitted to the master? I had some problems with the bt component in the mconfig component, but managed to get it to work perfectly.

**Comment by InfiniteYuan1** [comment]
I've already push it to github,commit id:[8277569a87717b308dfa8e977b8995a5b52eca3e](https://github.com/espressif/esp-mdf).You can try it. The problem you mentioned has been resolved.

**Comment by InfiniteYuan1** [comment]
@jesperrix Thank you for your approval.Please close this PR, if this is unnecessary.

**Pull request closed without merging**
